apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: test
  namespace: test
  labels:
    kargo.akuity.io/cred-type: git
stringData:
  repoURL: ${GITOPS_REPO_URL}
  username: ${GITHUB_USERNAME}
  password: ${GITHUB_PAT}
