apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: docker
  namespace: test
spec:
  subscriptions:
    - image:
        repoURL: nginx
        imageSelectionStrategy: SemVer
        semverConstraint: ^1.24.0
    - image:
        repoURL: prom/prometheus
        imageSelectionStrategy: SemVer
        semverConstraint: ^v2.0
