apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    kargo.akuity.io/authorized-stage: test:multiSourceSingleApp
  name: multiSourceSingleApp
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 15.7.1
      helm:
        valueFiles:
        - $values/charts/prometheus/values.yaml
    - repoURL: https://github.com/akolacz/argocd-multi-sources
      targetRevision: main
      ref: values
  destination:
    name: "in-cluster"
    namespace: default
